#ifndef __DEFAULTS_H__
#define __DEFAULTS_H__


#define DEFAULT_SCREEN_PHYSICAL_WIDTH 	1024
#define DEFAULT_SCREEN_PHYSICAL_HEIGHT	768	
#define DEFAULT_SCREEN_VIRTUAL_WIDTH	1024
#define	DEFAULT_SCREEN_VIRTUAL_HEIGHT	768
#define DEFAULT_SCREEN_BIT_DEPTH	16
#define	DEFAULT_SCREEN_X		0
#define	DEFAULT_SCREEN_Y		0

#endif
